# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-17 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReviews',
            fields=[
                ('movie_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('star_rate_movie', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('review', models.TextField(max_length=100)),
                ('fk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movies')),
            ],
            options={
                'ordering': ('movie_id', 'star_rate_movie'),
            },
        ),
        migrations.CreateModel(
            name='Reviewers',
            fields=[
                ('reviewer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, verbose_name='Reviewer Email')),
            ],
            options={
                'ordering': ('reviewer_id',),
            },
        ),
        migrations.AddField(
            model_name='moviereviews',
            name='fk_reviewer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Reviewers'),
        ),
    ]
