# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-17 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('uuid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=100)),
                ('cast', models.CharField(blank=True, max_length=100)),
                ('star_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('generic_type', models.CharField(choices=[('MV', 'Movies'), ('TV', 'TVShows')], default='MV', max_length=2)),
            ],
            options={
                'ordering': ('star_rate', 'uuid'),
            },
        ),
    ]
